"""Adicionando senha ao cliente

Revision ID: b6770e674903
Revises: c1c03b4f3b0b
Create Date: 2025-04-03 23:07:42.834777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6770e674903'
down_revision = 'c1c03b4f3b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(length=256), nullable=False))
        batch_op.drop_column('senha_hash')

    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(length=256), nullable=False))
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_column('senha')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
